version: 2

updates:
    -   commit-message:
            include: "scope"
            prefix: "composer"
        directory: "/"
        package-ecosystem: "composer"
        schedule:
            interval: "weekly"
        versioning-strategy: "increase-if-necessary"
